spring:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    Ali:
      ashique:
        ITCENTERFEESMANAGEMENT: DEBUG
  file: logging.log
